# py4lo
language: python

python:
  - "3.7"

cache: pip

before_install:
  - export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages/

# command to run tests and install dependencies
install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade pytest py codecov pytest-cov flake8 tox

  # dependencies
#  - python setup.py install --user
#  - python setup.py test

# script
script:
  - "flake8 ."
  - "pytest --cov-report term-missing --cov=datagouv_tools"
  - "pytest --cov-report term-missing --cov-append --doctest-modules datagouv_tools --cov=datagouv_tools"

after_success:
  - codecov