# py4lo
language: python

python:
  - "3.7"

cache: pip

before_install:
  - export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages/

# command to run tests and install dependencies
install:
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade pytest py codecov pytest-cov flake8

  # dependencies
  - sudo python3 setup.py install
  - sudo python3 setup.py test


# script
script:
  - "flake8 ."
  - "pytest --cov-report term-missing --cov=import_sirene"
  - "pytest --cov-report term-missing --cov-append --doctest-modules import_sirene.py --cov=import_sirene"

after_success:
  - codecov